name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
#  Firebase dependencies
  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0

#  Freezed dependencies
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

#  Riverpod dependdency
  flutter_riverpod: ^1.0.4

  pin_code_fields: ^7.4.0
  image_picker: ^0.8.5+3
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter pub run build_runner build
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
